[build-system]
requires = ["maturin>=1.0,<2.0", "setuptools_scm"]
build-backend = "maturin"

[project]
name = "transforms_py"
description = ""
readme = "README.md"
authors = [
    { name = "AP", email = "andras@artefacts.com" },
    { name="TN", email="tomo@artefacts.com"}
]
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License", 
    "Operating System :: OS Independent",
]
dependencies = []
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "pytest",
    "setuptools_scm",
    "maturin"
    ]

[tool.maturin]
module-name = "transforms_py._core"
python-packages = ["transforms_py"]
python-source = "src"

[tool.setuptools_scm]