def hello_from_bin() -> str: ...
def hello_transforms() -> str: ...
class PyRegistry:
    def __init__(self, cache_duration: float) -> None: ...
    def add_transform(self, x: float, y: float, z: float, qx: float, qy: float, qz: float, qw: float, timestamp: int, parent: str, child: str) -> None: ...
    def get_transform(self, parent: str, child: str, timestamp: int) -> tuple[float, float, float, float, float, float, float, int, str, str]: ...
